# Generated by Django 5.2.1 on 2025-05-25 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_challenge_course_alter_survey_support_option_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challengetask',
            options={'ordering': ['title'], 'verbose_name': 'Задание челленджа', 'verbose_name_plural': 'Задания челленджей'},
        ),
        migrations.AlterModelOptions(
            name='dayresult',
            options={'ordering': ['-created_at'], 'verbose_name': 'Результат дня', 'verbose_name_plural': 'Ежедневные результаты'},
        ),
        migrations.AlterField(
            model_name='challengetask',
            name='day',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='challengetask',
            name='setup',
            field=models.TextField(verbose_name='Установка'),
        ),
        migrations.AlterField(
            model_name='challengetask',
            name='title',
            field=models.TextField(verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='dailycycle',
            name='evening_wellbeing',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Самочувствие вечером'),
        ),
        migrations.AlterField(
            model_name='dailycycle',
            name='fail_result',
            field=models.TextField(blank=True, verbose_name='Что не получилось и почему'),
        ),
        migrations.AlterField(
            model_name='dailycycle',
            name='feelings',
            field=models.TextField(blank=True, verbose_name='Что почувствовал'),
        ),
        migrations.AlterField(
            model_name='dailycycle',
            name='manifest_type',
            field=models.CharField(blank=True, choices=[('calm', 'Спокойно'), ('focus', 'С фокусом'), ('pressure', 'С напором'), ('pace', 'С темпом')], max_length=20, verbose_name='Как хочет проявиться'),
        ),
        migrations.AlterField(
            model_name='dailycycle',
            name='morning_wellbeing',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Самочувствие утром'),
        ),
        migrations.AlterField(
            model_name='dailycycle',
            name='success_result',
            field=models.TextField(blank=True, verbose_name='Что удалось'),
        ),
    ]
