# Generated by Django 5.2.1 on 2025-05-26 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_challengetask_options_alter_dayresult_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.client', verbose_name='Пользователь')),
                ('schedule_type', models.CharField(choices=[('basic', 'Базовый'), ('focus', 'Фокусный'), ('hard', 'Жёсткий')], max_length=255, verbose_name='Тип расписания')),
            ],
            options={
                'verbose_name': 'Режим дня',
                'verbose_name_plural': 'Режимы дня',
            },
        ),
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название блока')),
                ('start_time', models.TimeField(verbose_name='Дата начала')),
                ('end_time', models.TimeField(null=True, verbose_name='Дата завершения')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_blocks', to='core.schedule')),
            ],
            options={
                'verbose_name': 'Блок режима дня',
                'verbose_name_plural': 'Блоки режимов дня',
                'ordering': ['-start_time'],
            },
        ),
    ]
