# Generated by Django 5.2.1 on 2025-05-29 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_schedule_timeblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('challenge_completed', 'Выполнение челленджа'), ('challenge_tasks_streak', 'Выполнение задач челленджа подряд'), ('sos_button_usage', 'Использование SOS Кнопки'), ('start_challenge', 'Начать челлендж'), ('daily_cycles_streak', 'Вести дневник'), ('bot_usage', 'Использование бота'), ('achievements_collection', 'Получение достижений')], max_length=100, verbose_name='Тип достижения')),
                ('value', models.IntegerField(verbose_name='Значение')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('motivation', models.CharField(max_length=255, verbose_name='Мотивация')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(choices=[('state_analysis', 'Анализ состояния'), ('select_month_goal', 'Выбор цели на 30 дней'), ('morning_message', 'Утреннее сообщение'), ('morning_extended_message', 'Утреннее сообщение (для платного тарифа)'), ('day_message', 'Сообщение днем'), ('evening_support', 'Сообщение-поддержка вечером'), ('select_overload_method', 'SOS Кнопка'), ('get_sos_help', 'SOS Кнопка (для платного тарифа)'), ('week_report', 'Еженедельный отчет'), ('month_report', 'Ежемесячный отчет')], max_length=100, unique=True, verbose_name='Тип промпта')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Промпт',
                'verbose_name_plural': 'Промпты',
            },
        ),
        migrations.AlterModelOptions(
            name='timeblock',
            options={'ordering': ['start_time'], 'verbose_name': 'Блок режима дня', 'verbose_name_plural': 'Блоки режимов дня'},
        ),
        migrations.AddField(
            model_name='clientchallenge',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='growth_zones',
            field=models.CharField(max_length=255, verbose_name='В каких сферах жизни хотел бы прокачаться'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='future_version',
            field=models.CharField(max_length=255, verbose_name='Чего хочет достигнуть через 30 дней'),
        ),
        migrations.CreateModel(
            name='ClientSosButtonUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_button_usages', to='core.client', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Нажатие SOS Кнопки',
                'verbose_name_plural': 'Нажатия SOS Кнопки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.achievement', verbose_name='Достижение')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='core.client', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Достижение пользователя',
                'verbose_name_plural': 'Достижения пользователей',
                'ordering': ['-created_at'],
                'unique_together': {('client', 'achievement')},
            },
        ),
    ]
