# Generated by Django 5.2.1 on 2025-06-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_achievement_prompt_alter_timeblock_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['value'], 'verbose_name': 'Достижение', 'verbose_name_plural': 'Достижения'},
        ),
        migrations.AddField(
            model_name='client',
            name='week_report_day',
            field=models.PositiveIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], default=6, verbose_name='День еженедельного обзора'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='achievement_type',
            field=models.CharField(choices=[('challenge_completed', 'Выполнение челленджа'), ('challenge_tasks_streak', 'Выполнение задач челленджа подряд'), ('sos_button_usage', 'Использование SOS Кнопки'), ('start_challenge', 'Начать челлендж'), ('daily_cycles_streak', 'Вести дневник'), ('bot_usage', 'Использование бота'), ('bot_usage_without_reset', 'Использование бота без полного сброса'), ('achievements_collection', 'Получение достижений')], max_length=100, verbose_name='Тип достижения'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.CharField(max_length=255, verbose_name='За'),
        ),
    ]
