# Generated by Django 5.2.3 on 2025-07-01 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_achievement_options_client_week_report_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('code', models.CharField(help_text='Только английские буквы, цифры и нижние подчеркивания', max_length=25, primary_key=True, serialize=False, verbose_name='Код')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('discount', models.PositiveIntegerField(verbose_name='Скидка в %')),
                ('activations_limit', models.PositiveIntegerField(verbose_name='Количество активаций')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='dailycycle',
            name='feelings',
            field=models.TextField(blank=True, verbose_name='Как себя чувствовал сегодня?'),
        ),
        migrations.AlterField(
            model_name='dailycycle',
            name='manifest_type',
            field=models.CharField(blank=True, choices=[('calm', 'Спокойно'), ('focus', 'С фокусом'), ('pressure', 'С напором'), ('pace', 'С темпом')], max_length=20, verbose_name='Какой настрой выбрал'),
        ),
        migrations.AddField(
            model_name='client',
            name='start_promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='core.promocode', verbose_name='Промокод'),
        ),
        migrations.CreateModel(
            name='PromoCodeActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата активации')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='core.client', verbose_name='Пользователь')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='core.promocode', verbose_name='Промокод')),
            ],
            options={
                'verbose_name': 'Активация промокода',
                'verbose_name_plural': 'Активации промокодов',
                'ordering': ['-date'],
            },
        ),
    ]
