# Generated by Django 5.2.3 on 2025-07-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_promocode_subscriptionprice_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='payment_method_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='Идентификатор метода оплаты'),
        ),
    ]
