# Generated by Django 5.2.3 on 2025-07-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_client_payment_method_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='discount',
        ),
        migrations.AddField(
            model_name='promocode',
            name='trial_days',
            field=models.PositiveIntegerField(default=14, verbose_name='Количество дней пробного периода'),
            preserve_default=False,
        ),
    ]
